#ifndef enum_h__
#define enum_h__

enum TAG_TYPE
{
	TAG_PLAYER, TAG_ENEMY,TAG_ITEM,TAG_PET, TAG_EFFECT, TAG_PLATFORM, TAG_UI , TAG_TYPE_END
};

enum COL_TYPE
{
	COL_RECT, COL_CIRCLE, COL_LINE ,COL_TYPE_END
};

enum LAYER_TYPE
{
	LAYER_BGA, LAYER_BGA_EFFECT, LAYER_PLATFORM, LAYER_OBJECT, LAYER_EFFECT, LAYER_UI, LAYER_TYPE_END,
};

enum PLAYER_STATE
{
	STATE_IDLE, STATE_RUN,	   STATE_BRAKE,		   STATE_TURN, STATE_ROLL, STATE_JUMP, STATE_FALL,
	STATE_DASH, STATE_DASH_END,STATE_DASH_END_AIR, STATE_HIT , STATE_DEAD, STATE_PRAY,STATE_RUNR,
	STATE_ATK_1,STATE_ATK_2,STATE_ATK_3,STATE_ATK_INAIR  , PLAYER_STATE_END
};

enum TILE_TYPE
{
	TILE_S1_S, TILE_S1_M, TILE_S1_L,TILE_S2_S,TILE_TYPE_END
};

enum AI_TYPE
{
	AI_IDLE, AI_JUMP, AI_FALL, AI_WALK,  AI_ATK_1 , AI_ATK_2 , AI_ATK_3 ,AI_ATK_4 ,AI_JUMP_ATK,AI_DOWN_ATK,
	AI_HIT,  AI_THROW, AI_DODGE, AI_IMPACT, AI_BACKFLIP, AI_DASH, AI_BRAKE , AI_BUFF,AI_READY_ATK, AI_DEAD,AI_INTRO,
	AI_READY,AI_TYPE_END
};

#endif // enum_h__
